front-end:
  container_name: front-end
  image: shridharpatil01/front-end
  ports:
    - "8080:8080"
  links:
    - quotes:quotes
    - newsfeed:newsfeed
  environment:
    APP_PORT: 8080
    STATIC_URL: http://localhost:8080
    QUOTE_SERVICE_URL: http://quotes:8001
    NEWSFEED_SERVICE_URL: http://newsfeed:8002
    NEWSFEED_SERVICE_TOKEN: T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX
  net: local_network
quotes:
  container_name: quotes
  image: shridharpatil01/quotes
  ports:
  - "8001:8001"
  net: local_network  
newsfeed:
  container_name: newsfeed
  image: shridharpatil01/newsfeed
  ports:
  - "8002:8002"
  net: local_network
